---
title: "Lifespan Schedule Spring 2025"
author: "Brian Holt"
date: "`r  Sys.Date()`"
output:
  html_document:
    config:
      search: yes
      toc:
        after: |
          <!-- <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li> -->
        before: |
          <li><a href="./">Lifespan Psychology Spring 2025 schedule</a></li>
        scroll_highlight: yes
      toolbar:
        position: fixed
    css: "style.css"
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
description: This is a minimal example of using the rmarkdown package for Lifespan
  psychology
link-citations: yes
bibliography: Lifespan.bib
biblio-style: apalike
---

# Week 2 April 14 {#Week2}
## Orientation

There are several things to think about this week. And I'm probably giving you too much to do so I want you to be thoughtful about your limits and to focus on the things that interest you.

One broad way to look at lifespan psychology is to see how textbooks break the units up:
Developmental psychology textbooks typically break every unit into three sections and sometimes that shows up in each chapter. Basically biological section cognitive section and a social / emotional section.

I like to call this the Humpty Dumpty approach to studying people. We break complex individuals into sections.

Biological |  Cognitive | Social
---|---|---|
What biological changes are there?| What cognitive changes?| what social/emotional?|
E.g.,: number of neurons| short term memory capacity|ability to code shift

This pattern is repeated throughout the text. And it's not a bad framework.

Because this is a psychology class I prefer to spend time thinking about psychology and not biology. There are cases where we've got pretty clear evidence that biological insults can lead to psychological impact. And in those situations I reluctantly like to learn a little bit about them. Reluctantly because I find that biological insults are pretty rare and knowing about them and more generally how the brain works doesn't often lead to knowing how to handle a particular psychological situation.  Just because my kid has an immature brain and can't tolerate frustration does nothing for me when I am trying to actually help him. 

I actually think that a lot of the biological influences on human behavior, though important, are really secondary to how complex humans are when it comes to their language and cognitive abilities. But that's my perspective.

This week we sprint through a few chapters and think about prenatal, infants, and toddlers.  

## Supporting materials

### Chapter 1 & 2 Learning Objectives
Go to our canvas shell for these

## Read/watch some stuff

1. [Watch video on writing guide](https://youtu.be/ytWuC6tns_w){target="_blank"}

2. Read/skim @schwartzImportanceStupidityScientific2008.  Take notes on more then just the content.  Note your emotional reactions and where your mind goes. Added 1/9/23:  Here is the direct link to the article (so you don't have to jump to the bottom of this document to get it): [Importance of Stupidity, Schwartz 2008](https://journals.biologists.com/jcs/article/121/11/1771/30038/The-importance-of-stupidity-in-scientific-research){target="_blank"}

```{block,type='blueBackground'}
A few things:

a) note that the link inside the 2008 for the Schwartz article doesn't take you to the article; it takes you to the references in the schedule.  There, you will sometimes find the link to the actual article; other times you may have to use our library's database. I've added a direct, though, in that paragraph above.

b) If you've taken one of my classes in the recent few years you have read The Schwartz article and so I'm sorry that you get to read it again. However, there's a good reason to review it, and another reason for me assigning it is that not everybody who is in this life span class has had my other classes. 
```

<br>
<br>
3. Read [William perry developmental stages as summarized by William Rappaport](https://cse.buffalo.edu/~rapaport/perry.positions.html){target='_blank'} @rappaportWILLIAMPERRYSCHEME2018

## Do some stuff

A. Synthesize those readings above: @rappaportWILLIAMPERRYSCHEME2018, @schwartzImportanceStupidityScientific2008, in your google document.


```{block, type='blueBackground'}

Please do not summarize these articles.  Synthesize.  Use the lecture just below to help

```

  * [Lecture on one way to write a synthesis paper--This should pop-up a new tab/window but you'll have to log in to canvas because that is how the videos are stored.](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=44737fc2-c8cb-4286-9dcf-ac4b011de256){target='_blank'}

  * [Quick 6 min intro on critical thinking](https://www.youtube.com/watch?v=3CkLAMLTkmI&feature=youtu.be){target='_blank'}


B.  In your one document to rule them all, write 3 questions you have about each of the first 2 chapters in your textbook. You don't need to share the google doc again, but pick 1 question from the list you generated, and post it in the [#student-generated-question discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/360693){target='_blank'}.

C. When you have finished week 2's work and have put your writings into your google doc, copy your google doc's link and share it to [#week-2 Discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/360695){target='_blank'}



# Week 3 Apri 21 {#Week3}

See canvas for study guides


## Read some stuff

1. Read  [Textbook, chapter 3: Infancy and toddlers](https://socialsci.libretexts.org/Bookshelves/Human_Development/Book%3A_Lifespan_Development_-_A_Psychological_Perspective_(Lally_and_Valentine-French)/03%3A_Infancy_and_Toddlerhood){target="_blank"}

2. Read Chapter 4 from your [Textbook](https://socialsci.libretexts.org/Bookshelves/Human_Development/Book%3A_Lifespan_Development_-_A_Psychological_Perspective_(Lally_and_Valentine-French)/04%3A_Early_Childhood){target='_blank'}


## Do some stuff


1. [Do this case study about a 9 month old](https://docs.google.com/document/d/1Rv6Ll4eyxhb58BbklUuBKXgUo_3lsPtWKWBoiiusxdg/edit?usp=sharing){target='_blank'}

2. What are the differences between the following (there can also be overlap):

  * sensation

  * perception

  * cognition

3. How can you tell whether a 1 year old is doing one or the other of these?  This is a very challenging question, likely too challenging for our level.  But how would you approach organizing some ideas, questions, readings?  Don't try to come to a concrete answer...you don't have time. 


4.  In your one document to rule them all, write 3 questions you have about  chapters 3 and 4 in your textbook. You don't need to share the google doc again, but pick 1 question from the list you generated, and post it in the [Student generated questions](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/368958){target='_blank'}.

5. When you have finished Week 3and have put your writings into your google doc, copy your google doc's link and share it to [#week-3 Discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/368957?module_item_id=1787793){target='_blank'}



# Week 4 April 28 {#week4}

## Read/watch some stuff

1. [Read Chapter 5, Middle and Late Childhood https://socialsci.libretexts.org/Bookshelves/Human_Development/Book%3A_Lifespan_Development_-_A_Psychological_Perspective_(Lally_and_Valentine-French)/04%3A_Early_Childhood](https://socialsci.libretexts.org/Bookshelves/Psychology/Developmental_Psychology/Lifespan_Development_-_A_Psychological_Perspective_2e_(Lally_and_Valentine-French)/05%3A_Middle_and_Late_Childhood){target='_blank'}

<br/>

```{block, type='blueBackground'}

Students sometimes struggle with this next set of instructions.  When you go to this website below, you will need to scroll down to see the 3 other Volumes of the book.  I think you may have to click the "buy set of 4" to open the menu...you <u>are not actually</u> going to buy these books!

Read the titles within each volume. I have the book and will give you the full chapter to read. Just let me know which chapter title and which book Volume you are interested in.
```

<br/>

2. Pick a chapter from one of the 4 volumes of the [Handbook of Developmental Psychology https://www.wiley.com/en-us/Handbook+of+Child+Psychology+and+Developmental+Science%2C+Volume+2%2C+Cognitive+Processes%2C+7th+Edition-p-9781118136782](https://www.wiley.com/en-us/Handbook+of+Child+Psychology+and+Developmental+Science%2C+Volume+2%2C+Cognitive+Processes%2C+7th+Edition-p-9781118136782){target='_blank'}

<br/>

```{block, type='blueBackground'}
<span class='sidenote'>This resource has 4 volumes </span>
The link above goes to the 2nd volume of the set. At the bottom, you can see the table of contents for that 2nd volume.

However, just above the table of contents for volume 2, there are 3 URL links to volumes 1, 3, and 4, each with their own table of contents.  

You'll need to skim all of those table of contents to find something interesting, and typically it will not be found in the first volume.  
```

<br/>
3. Send your choice to your instructor via an email brian.holt@seattlecolleges.edu, not canvas messaging. 


## Do stuff

  1. [Case Study 2 https://docs.google.com/document/d/1tIxkbn0Tm2X37rY6fqRF5yCjFk-rkwQRu7yqMk-pkLM/edit?usp=sharing](https://docs.google.com/document/d/1tIxkbn0Tm2X37rY6fqRF5yCjFk-rkwQRu7yqMk-pkLM/edit?usp=sharing){target='_blank'}

  2. Make a simple table to compare the first 3 phases of Piaget and Erickson.
 
   * For instance you might have a column of for each theorist, a row for each stage of the first 3 stages, and then a column that you share some bullet like notes that do some comparison
<div class="sixth"> you must cite the work of C. Buster Antonio added as a reference to the bottom. Please don't refer to Buster in the text; just at the bottom.</div></p>
   * a comparison could be on how they are different, or where they support one another, or even some questions you may have about the theories and or phases/stages. 
 
 3. Find some online sources that describe in your google document the kind of chores a 6 year old child could perform. List 4 or 5  (Be sure to include references).  Using one of the cognitive theories of development (e.g., Vygotsky, Piaget, Information Processing) justify why the 6 year old would be able to do one (just 1) of those chores.  

 4. Do a Survey on [how important sex is to you](https://docs.google.com/forms/d/e/1FAIpQLSfpnmmTRSjBNa50tTLHsUX3venfF8aTe85CCXVha6cFeO_Sew/viewform){target='_blank'}. If you have done this in my other classes, please don't do it again.   This might seem out of the blue, which it is, but there are several things I hope to accomplish here.  <span style="color: red;">Don't put your score in the google doc.</span>

  
    * it's optional and anonymous. I do require that you put your age and sex-assigned-at-birth because that is how the original study was conducted.  <span style="color: red;">Don't put your score in the google doc.</span>
  
     * It gives us a chance to talk about:
  
        * hypothetical constructs
    
         * difficulty in social science research
  
          * statistics

<span style="color: red;"> Have I said to not put your score in the google doc?</span>


5. Post your work to [#week4](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/368960?module_item_id=1787800){target='_blank'} .


# Week 5 May 5 {#week5}


## Orientation

I've been re-reading the lifespan textbook and I am wondering if there some ways to think about how text books organized information the net as possible that they are oversimplifications.  

Here are some examples:

<p style = 'text-decoration: underline'>Claim:</p>

  >In addition to dopamine, the adolescent brain is affected by oxytocin which facilitates bonding and makes social connections more rewarding.

No reference though.  Possibly connects to Dobbs listed just above.  My quick check on that resource goes to a national geographic article.  That's weird.  And my knowledge of these sorts of claims comes from my experience that most of those research claims are hypothetical, or based on other mammals.  

I worry that this bit about oxytocin is overgeneralized (cf [replication crisis](https://www.vox.com/science-and-health/2019/2/13/18221876/oxytocin-morality-valentines){target='_blank'})

As you read the textbook, keep track of its claims that either don't have references, or give you the vibes that there is an oversimplification.


#### Chapter 6 Learning Objectives

 
## Read some stuff


1. [Read Chapter 6, Adolescence](https://socialsci.libretexts.org/Bookshelves/Human_Development/Book%3A_Lifespan_Development_-_A_Psychological_Perspective_(Lally_and_Valentine-French)/06%3A_Adolescence){target='_blank'}

   * While reading, take some notes regarding textbook claims that might sounds too simple.  Keep track of their locations.

2. Read your chosen article from handbook volume.  


## Do some stuff

A. Write a summary..yes, a summary of what you read from your chosen chapter/section from the Developmental Handbook [@lernerHandbookChildPsychology2015] that you asked for in week 5.  The goal is to write for your understanding, which means you may want to write a bit about questions you have, connections to your work/childhood/relevant stuff to you. 

B. I want you to have questions about this article you read.  So, please list at least 3. Post 1 in the [student generated Q discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/372033){target='_blank'}

C. How, go to chat gpt: https://chat.openai.com/

  * You will need to register an account with them.
  * Think of gpt as a person to converse with.  Be skeptical of it, so if it says something as if it were all knowing, don't believe it.  I am still working on the right metaphor here.  Like, what if you had access to a professor in a discipline and could ask them anything?  And that you could treat them as someone who actually doesn't know more than you, is biased, narrow minded, that you are essentially above them in status and so if they say something, you don't reflexively think they are right and are also not afraid of calling out their B.S. 

  * Give chat gpt an introduction to your question.  You are framing the conversation here. 
  * ask your question
  * when it answers, use the critical thinking standards found in the syllabus to think about its answer.  Is there an area that is weak?  Ask GPT to explain, to reconcile itself, to consider things it left out.  
  * Highlight and copy the chat gpt thread and paste it into your google doc.  You might need to edit the formatting a bit.  

D. Share your notes/questions in from #1 above regarding textbook claims that are either missing references, or that you feel skeptical in its presentation.  If you have done some extra research on these topics, include that as well; I think future weeks we may come back to this. 

E. You might want to use chat gpt to justify/critically analyze the textbook. 

F. Share your work in the [#week 5 discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/372013?module_item_id=1797542){target='_blank'}


# Week 6 Adolescence redux May 12 {#week6}

Last week was a mix of self-reflection assignments and article summary.  But we didn't get into much of the adolescent part of development, and really, it's an important period of time for humans.

Consider some of these concepts:  

- Risks

- Fables

- Formal Reasoning

- Identity Formation

These are some big ideas and issues. 

## Read some stuff

1. Without putting too much research into it, what are some examples of risky behavior that come to mind? What makes them risky? Consider the ideas of control, power, parental fears, etc. Write down your ideas in your one google doc.

2. [Revisit Chapter 6, Adolescence, as needed](https://socialsci.libretexts.org/Bookshelves/Human_Development/Book%3A_Lifespan_Development_-_A_Psychological_Perspective_(Lally_and_Valentine-French)/06%3A_Adolescence){target='_blank'}

3. Read/skim [Chapter 21 from Volume 3, The development of sexuality](https://canvas.seattlecolleges.edu/courses/32787/files?preview=16949720){target='_blank'} @lernerHandbookChildPsychology2015


## Do some stuff

A. Complete [Case 3](https://docs.google.com/document/d/1x8KwE-_ZGMRZcqE1U5L0r8KeXZdBrlHvogAM_mT1Aq4/edit){target='_blank'}

B. Then, dictate your ideas about case 3 using some speech to dictation software/app.

* Using some speech to text dictation software (found in google docs on chrome browsers, or also found on most smart phones), imagine you are explaining to another person what you wrote down for case #3 assigned above.  Don't read what you wrote. Talk about the ideas. In other words, imagine explaining to a friend what you wrote down above. 

* Just talk as if you were explaining it.  Don't worry about the "um's" or  "uh's"...  Just talk.  Don't worry about word choices.  Just talk about what you wrote. If you need to remind yourself what you wrote, that's fine.  Stop the speech to text dictation, skim what you wrote, and the go back to explaining it with verbal language.  

* Also, don't read along with your talking. Look away from the screen while talking..you can get distracted if you try to read along. 


C. Write a bit about risks now that you've done some reading about it.  Some questions to consider:

  * what makes something risky?  Who owns the term? 
  * what are areas of disagreement between parents and adolescents about risky behavior, and what can be done to bring them together..to see eye to eye so to speak? 
  * Put your thoughts, questions, answers into your google document

D. Ask Chat gpt what it thinks are cliche's about adolescence.  Ask it about cultural differences.  Ask it meta questions.  In other words, don't think of chat gpt as a source of content or correct, objective, knowledge.  Think of it instead as someone who does not think critically but has access to a lot of information and can emotionally handle tough questions (because, of course, it's not human.)

E. Post your work to the [week 7 discussion](https://canvas.seattlecolleges.edu/courses/32787/discussion_topics/373251?module_item_id=1801413){target='_blank'}

 


# Appendix

## Using the library {#useLibrary} 

The library has set up a simple library guide for our class.  You can find it here: [Abnormal Psychology library guide](https://libguides.northseattle.edu/psych220). I

```{block, type='blueBackground'}
<span class='sidenote'>Note: Don't pay for articles</span>

One important word of advice is to never pay for a scholarly article. If you go online and use Google, or even Google Scholar to find online sources, you may be directed to the publication that will charge you a large amount of money to access just one article.  So don’t do that.

Generally there are ways to get articles through our library, so don't pay for articles.
```


To get started with our readings, you'll need to use our Library (online, of course) to obtain many of the articles.  

Finding journal articles is a skill that gets better with practice.  This happens to be why Librarians are so helpful.  They've actually been trained so if you can't find an article, it's okay to ask librarians for help.  

In fact, here is how you can [get help from North Seattle's library staff](https://libguides.northseattle.edu/welcome/askus). 



### Relationship of an article to its Journal

Using hierarchies helps us organize information. Journal articles, or for that matter the file directories on your computer, work somewhat like an address for a person's home. There are several different parts that give us information to track down and locate whatever it is we're looking for, be it a computer file, or Journal article. Basically, a journal article  has the following components, some of which may be familiar to you :

      Database (of periodicals)
        Periodical (eg., magazine, newspaper, scholarly journal)
         Year (of publication)
           Volume Number
            Volumne Issue number
             Page Number (optional, often unnecessary)
               Article Title
                  Author

So, to find an article, you'll need to know the parts above.  When you are given a list of references, or citations, nearly all of the information needed above is given to  you.  What is not given, or at least is done implicitly with web searches, is access to the top part, the database.  

#### Here is a typical citation:

>Author(s). (year of pub). "Article Title." <span class='underline'>Periodical title</span>. Volume Number (issue number).

The information in a citation isn't presented in the same hierarchy as above, but all of the necessary parts are there.  

Here is an example citation (reference) for something we may read.  Can you identify the periodical?

>Jay Efran, Michael Lukens, Mitchell Greene. 2007. “Defining Psychotherapy: The Last 25 Years Have Taught Us That It’s Neither Art nor Science.” <span class='underline'>Psychotherapy Networker</span> 31 (2). 

Most of the items in the list above are self-explanatory. I want to focus a bit about periodicals.

```{block, type='blueBackground'}
<span class='sidenote'>Note on formatting citations: underlining publication titles</span>

In print, publication titles are *italicized*.  I have a very hard time noticing that subtle font.  

When you submit a written manuscript for printing, publication titles are <span style='text-decoration: underline'>underlined</span> because traditionally manuscripts were typed with typewriters, and to be able to type italicized words required an entire additional alphabet represented in the hammers.  So, underlining was how you could emphasize a word, and the printer--a physical person--could notice the author's formatting intent and correctly publish the final product in italics. 

It's a bit different now with our computers, obviously.  Still, I have a hard time seeing italicized words and will occasionally use underline. 

So, sometimes I'll underline pub titles, sometimes I'll italicize. I have no rule on this.  I am chaos manifested.  Beware. 
```

#### Periodicals

These are just the names of the major publication. _The New York Times_, is colloquially known as a newspaper but technically it is a periodical. <span class='underline'>The Journal of Abnormal Psychology</span> is also a periodical. 

When we search for articles, we have to first know which journal, or periodical, owns that article.  So it is a little counter intuitive but once we have identified an article we would like to read, we have to first find out whether or not our College has access to that periodical.  

To do that, we have to use our colleges periodical locator.

### Finding a journal using Periodical locator

#### Periodical locator {#PeriodicalLocator} 

Notice the first link within [North's Article page](https://libguides.northseattle.edu/welcome/articles){target="_blank"}.  It should say "Periodical Locator"

There are many databases, inside of these databases are pages of journals, and inside those journals are articles. 

**We need to use the periodical locator to determine which database houses which periodical.  With that, we can then open up that periodical and get the article**


```{block, type='blueBackground'}
<span class='sidenote'>Note on 'free' articles and tuition/fees</span>

Part of the fees that you pay as a student are used to pay subscriptions for these periodical databases. We have a small, but pretty good selection. Major universities have much larger collections due to their size and tuition/fee structure.

So in a way, you are **not** actually getting this for free because you are paying for library access. That's the benefit of taking classes from a college. If you were not an active student, you would not be able to see many of these articles.

So, download them all!
```

##### Here's the main point: {#libraryMainPoint} 

I've given you a list of Articles to read. To read them, you must first find them; some will be out in the internet, some will be in our schools' databases. So, use the information I've given you to find out which location (database, Wikipedia, Google, Google scholar) you'll need to search to obtain the full article. You will start by using the periodicals locator tool.

Let's use that @efran_defining_2007 article.  

1. Go to  [North's Article page](https://libguides.northseattle.edu/welcome/articles) and click on the periodical locator.  

2. Type in the name of the periodical for Efran's piece. 

You will see a link with the periodical's name.  Go ahead and click on this but beware of the next instruction:

3. Once you have clicked on that link you may want to start searching within that publication. But do not do that. Instead, notice a little bit further down the search box you should see something that says "View online" and beneath that you should see something that says "proquest research library".   It’s this piece we need.

    That Proquest research library is the database that you've all paid fees to access. So you need to remember that database name.  Or, I think now you can just click on it and skip to step 8.

4. While remembering that database name, you need to go back to  [North's Article page](https://libguides.northseattle.edu/welcome/articles).

5. Notice what is presented here.  You can see Periodical locator, but notice "A to Z" list of databases.  (You might also notice just below two links; one to academic search and the other to Proquest).



6. Click on "A to Z"

7. You might notice that there are 67 databases that North Seattle has premium access to. In our case we're going to be looking for the proquest direct database. And we can either click on the letter "P" or we can just type in proquest direct.


```{block, type='blueBackground'}
<span class='sidenote'>Note on Popular sources</span>

You may also notice the little tag "popular" next to proquest link.  That's an indicator that the articles are not peer reviewed and so aren't exactly cutting edge science. Even though this particular journal we are looking for, _Psychotherapy Networker_, is flagged as a popular type, it is a place for therapists to share their thoughts on the profession so there is a lot of value in it.

For help in distinguishing the different types of sources, the library has some guides:

* [Scholar vs popular](http://libguides.northseattle.edu/c.php?g=97441&p=630690)

* [Find Scholarly Journals](http://libguides.northseattle.edu/c.php?g=97441&p=630669)

```

8. Opening Proquest from your home, or remotely, you will need to validate your credentials. In other words, you need to prove that your are in fact a student of North Seattle before you can continue, which is why you've been prompted for your @ seattlecolleges.edu email and password. Once you do that you'll then be able to see inside of the proquest database. Then you can now search for the article.

     - 8a. If you don't know your @ seattlecolleges.edu email, or email password, you can go to this location [https://tools.seattlecolleges.edu/Initialize/resetmypassword](https://tools.seattlecolleges.edu/Initialize/resetmypassword){target='_blank'} to update it, reset/change the password. If you still can't get access, let me know.
<p>     </p>
9. You should see a simple search box, where you can enter important bits of information. I often start with the author's last name, in this case, Efran,and then some unique identifying feature of the article. A few key words of the article title, or perhaps the full article title will be useful.

But notice that next to the text boxes there are drop down menus. You need to use those, otherwise the search engine will just search for your terms anywhere in the document and will provide too many 'hits'. Instead, you should indicate ‘Efran’ as author, and "defining" in the document title. (of course, you could search any way you like).

When you search for those two terms in their respective fields, you will get two hits and one of them is the article we need. You should notice that it is a full text, not all databases provide full text documents. But in this case it's a full text. You can either print it or read it online.

Yay.  Now you can find the other articles. 

### A quick video of the process (some day once ctclink matures)

## Anatomy of a journal article

#### Title
#### Abstract
#### Introduction
##### Lit review
##### hypothesis
#### Methods
##### Participants
##### Materials
##### Procedure
#### Results
#### Discussion
#### References




`r if (knitr:::is_html_output()) '
# References {-}
'`
